# See https://docs.aspect.build/v/workflows/config
---
env:
  DENO_DIR: /mnt/ephemeral/caches/.deno
workspaces:
  - .
  - e2e/workspace:
      tasks:
        format:
          without: true
        buildifier:
          without: true
tasks:
  format:
    soft_fail: false
  buildifier:
  test:
