# See https://docs.aspect.build/v/workflows/config
---
env:
  DENO_DIR: /mnt/ephemeral/caches/.deno
workspaces:
  - .
  - e2e/workspace:
      tasks:
        - test:
            queue: aspect-small-amd64
        - format:
            without: true
        - buildifier:
            without: true
        - configure:
            without: true
tasks:
  - format:
      soft_fail: false
      queue: aspect-small-amd64
  - buildifier:
      queue: aspect-small-arm64
  - configure:
      queue: aspect-small-arm64
  - test:
  - warming:
      queue: aspect-warming
