workspace(name = "genrule_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# See the note in rules_deno/CONTRIBUTING.md to use the local source for rules_deno rather than release
http_archive(
    name = "dev_aspect_rules_deno",
    sha256 = "ca07f393896e555fba89066cb343638ce8cc859d07f47ba54ffd308394610bce",
    urls = [
        "https://github.com/aspect-dev/rules_deno/releases/download/0.1.0/rules_deno-0.1.0.tar.gz",
    ],
)

load("@dev_aspect_rules_deno//deno:repositories.bzl", "deno_register_toolchains", "rules_deno_dependencies")

# This just gives us bazel-skylib
# We could just as easily install that ourselves instead of calling this helper.
rules_deno_dependencies()

deno_register_toolchains(
    name = "deno1_14",
    deno_version = "1.14.2",
)
