# Override http_archive for local testing
local_repository(
    name = "aspect_rules_deno",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_deno setup #
######################

load("@aspect_rules_deno//deno:dependencies.bzl", "rules_deno_dependencies")

# Fetches the rules_deno dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
rules_deno_dependencies()

load("@aspect_rules_deno//deno:repositories.bzl", "LATEST_DENO_VERSION", "deno_register_toolchains")

deno_register_toolchains(
    name = "deno",
    deno_version = LATEST_DENO_VERSION,
)
