"""BUILD definition for format binary
This is in its own package to not trigger eager fetches.
"""

load("@aspect_rules_lint//format:defs.bzl", "format_multirun")

package(default_visibility = ["//:__subpackages__"])

# Starlark-only formatter for the dedicated buildifier CI step.
# See https://docs.aspect.build/cli/migration/buildifier.
format_multirun(
    name = "buildifier",
    starlark = "@buildifier_prebuilt//:buildifier",
)
